# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Pneumonia finder")
        MainWindow.resize(349, 462)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.overview_button = QtWidgets.QPushButton(self.centralwidget)
        self.overview_button.setGeometry(QtCore.QRect(260, 10, 75, 23))
        self.overview_button.setObjectName("overview_button")
        self.pneumonia_button = QtWidgets.QPushButton(self.centralwidget)
        self.pneumonia_button.setGeometry(QtCore.QRect(260, 420, 75, 23))
        self.pneumonia_button.setObjectName("overview_button")
        self.normal_button = QtWidgets.QPushButton(self.centralwidget)
        self.normal_button.setGeometry(QtCore.QRect(10, 420, 75, 23))
        self.normal_button.setObjectName("overview_button")
        self.invisible_label = QtWidgets.QLabel(self.centralwidget)
        self.invisible_label.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.invisible_label.setObjectName("invisible_label")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(260, 40, 70, 13))
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label.setObjectName("label")
        self.invisible_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.invisible_label_2.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.invisible_label_2.setObjectName("invisible_label_2")
        self.result_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.result_label_2.setGeometry(QtCore.QRect(260, 60, 70, 13))
        self.result_label_2.setText("")
        self.result_label_2.setObjectName("result_label_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 331, 331))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 349, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Pneumonia finder", "Pneumonia finder"))
        self.pneumonia_button.setText(_translate("MainWindow", "Пневмония"))
        self.normal_button.setText(_translate("MainWindow", "Норма"))
        self.overview_button.setText(_translate("MainWindow", "Обзор"))
        self.invisible_label.setText(_translate("MainWindow", "Распознано:"))
        self.label.setText(_translate("MainWindow", "Выберите изображение "))
        self.invisible_label_2.setText(_translate("MainWindow", "Верный ответ:"))
